version: "3.7"
services:
  app:
    build:
      target: base
      context: .
    volumes:
      - ./:/app
    env_file:
      - local.env
    command: ["tail", "-f", "/dev/null"]
  db:
    image: mysql/mysql-server:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=s3cret_password
      - MYSQL_ROOT_HOST=%
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:3306
