version: "3.7"
services:
  app:
    build:
      target: base
      context: .
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./:/app
    env_file:
      - local.env
    command: ["tail", "-f", "/dev/null"]
  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - local.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--password=S3cret_password"]
      interval: 10s
      timeout: 3s
      retries: 30
    ports:
      - "3306:3306"
